"""LLM-based generation of today session execution content.

Generates instructions, steps, and coach insight for today's training sessions.
"""

from __future__ import annotations

from loguru import logger
from pydantic import BaseModel, Field
from pydantic_ai import Agent

from app.coach.config.models import USER_FACING_MODEL
from app.services.llm.model import get_model
from app.workouts.llm.logging_helpers import (
    log_llm_extracted_fields,
    log_llm_raw_response,
    log_llm_request,
)


class WorkoutStepOutput(BaseModel):
    """Workout step output schema for LLM."""

    order: int = Field(description="Step order (1-indexed)")
    name: str = Field(description="Step name (e.g., Warm-up, Main, Cooldown)")
    duration_min: int | None = Field(description="Step duration in minutes", default=None)
    distance_km: float | None = Field(description="Step distance in kilometers", default=None)
    intensity: str | None = Field(
        description="Step intensity: easy | steady | tempo | threshold | vo2",
        default=None,
    )
    notes: str | None = Field(description="Optional step-specific notes", default=None)


class TodaySessionContent(BaseModel):
    """Today session execution content generated by LLM."""

    instructions: list[str] = Field(
        description="Execution instructions (3-5 bullets max, execution cues not metrics)",
        min_length=1,
        max_length=5,
    )
    steps: list[WorkoutStepOutput] = Field(
        description="Structured workout steps (default: warm-up, main, cooldown)",
        min_length=1,
    )
    coach_insight: str = Field(
        description=(
            "Coach insight explaining why today matters, "
            "referencing recent load and recovery implicitly, "
            "including conditional advice"
        ),
        min_length=50,
    )


def build_today_session_prompt(
    session_title: str,
    session_type: str | None,
    duration_minutes: int | None,
    distance_km: float | None,
    intensity: str | None,
    notes: str | None,
    is_rest_day: bool = False,
    is_completed: bool = False,
    actual_duration_minutes: int | None = None,
    actual_distance_km: float | None = None,
) -> str:
    """Build prompt for generating today session content.

    Args:
        session_title: Session title
        session_type: Session type (e.g., 'easy', 'tempo', 'long')
        duration_minutes: Planned duration in minutes
        distance_km: Planned distance in kilometers
        intensity: Intensity level
        notes: Session notes
        is_rest_day: Whether this is a rest day
        is_completed: Whether this session has been completed
        actual_duration_minutes: Actual duration if completed
        actual_distance_km: Actual distance if completed

    Returns:
        Complete prompt string
    """
    if is_completed:
        parts = [
            "SYSTEM:",
            "You are an AI endurance coach providing post-workout analysis and feedback.",
            "",
            "TASK:",
            "Analyze the completed session, compare actual execution to what was planned, and provide coach insight.",
            "",
            "RULES:",
            "- Instructions: 3-5 bullets analyzing what happened, compliance with plan, execution quality",
            "- Steps: Show what was planned vs what was executed (if available)",
            "- Coach insight: Analyze execution, compliance, what went well, what to adjust",
            "- Reference how this session fits into overall training progression",
            "- Use synthesis and judgment language, not deterministic rules",
            "- Do NOT say 'rule-based', 'algorithm', or list raw metrics",
            "",
            "PLANNED SESSION:",
            f"Title: {session_title}",
        ]
        if session_type:
            parts.append(f"Type: {session_type}")
        if duration_minutes:
            parts.append(f"Planned Duration: {duration_minutes} minutes")
        if distance_km:
            parts.append(f"Planned Distance: {distance_km} km")
        if intensity:
            parts.append(f"Planned Intensity: {intensity}")
        if notes:
            parts.append(f"Notes: {notes}")

        parts.append("")
        parts.append("ACTUAL EXECUTION:")
        if actual_duration_minutes:
            parts.append(f"Actual Duration: {actual_duration_minutes} minutes")
            if duration_minutes:
                delta = actual_duration_minutes - duration_minutes
                parts.append(f"Duration Delta: {delta:+d} minutes")
        if actual_distance_km:
            parts.append(f"Actual Distance: {actual_distance_km} km")
            if distance_km:
                delta = actual_distance_km - distance_km
                parts.append(f"Distance Delta: {delta:+.2f} km")
    else:
        parts = [
            "SYSTEM:",
            "You are an AI endurance coach generating daily execution guidance.",
            "",
            "TASK:",
            "Generate execution instructions, structured steps, and coach insight for today's session.",
            "",
            "RULES:",
            "- Instructions: 3-5 bullets, execution cues (not metrics), actionable",
            "- Steps: Default warm-up / main / cooldown structure",
            "- Rest days: Include optional mobility / walk steps",
            "- Coach insight: Explain why today matters, reference recent load + recovery implicitly",
            "- Include conditional advice (e.g., 'if it feels forced...')",
            "- Use synthesis and judgment language, not deterministic rules",
            "- Do NOT say 'rule-based', 'algorithm', or list raw metrics",
            "",
            "SESSION DETAILS:",
            f"Title: {session_title}",
        ]
        if session_type:
            parts.append(f"Type: {session_type}")
        if duration_minutes:
            parts.append(f"Duration: {duration_minutes} minutes")
        if distance_km:
            parts.append(f"Distance: {distance_km} km")
        if intensity:
            parts.append(f"Intensity: {intensity}")
        if notes:
            parts.append(f"Notes: {notes}")
        if is_rest_day:
            parts.append("Rest Day: Yes")

    parts.append("")
    parts.append("OUTPUT FORMAT:")
    parts.append("Return JSON with instructions (list of strings), steps (list of step objects), and coach_insight (string).")

    return "\n".join(parts)


def _validate_content_type(content: object) -> None:
    """Validate that content is of the expected type.

    Args:
        content: Content to validate

    Raises:
        TypeError: If content is not TodaySessionContent
    """
    if not isinstance(content, TodaySessionContent):
        raise TypeError(f"LLM returned invalid type: {type(content)}")


async def generate_today_session_content(
    session_title: str,
    session_type: str | None = None,
    duration_minutes: int | None = None,
    distance_km: float | None = None,
    intensity: str | None = None,
    notes: str | None = None,
    is_rest_day: bool = False,
    is_completed: bool = False,
    actual_duration_minutes: int | None = None,
    actual_distance_km: float | None = None,
) -> TodaySessionContent:
    """Generate today session execution content via LLM.

    Args:
        session_title: Session title
        session_type: Session type
        duration_minutes: Planned duration in minutes
        distance_km: Planned distance in kilometers
        intensity: Intensity level
        notes: Session notes
        is_rest_day: Whether this is a rest day
        is_completed: Whether the session has been completed
        actual_duration_minutes: Actual duration in minutes (if completed)
        actual_distance_km: Actual distance in kilometers (if completed)

    Returns:
        TodaySessionContent with instructions, steps, and coach_insight

    Raises:
        ValueError: If LLM fails to generate valid content
        RuntimeError: If LLM call fails
    """
    model = get_model("openai", USER_FACING_MODEL)
    prompt = build_today_session_prompt(
        session_title=session_title,
        session_type=session_type,
        duration_minutes=duration_minutes,
        distance_km=distance_km,
        intensity=intensity,
        notes=notes,
        is_rest_day=is_rest_day,
        is_completed=is_completed,
        actual_duration_minutes=actual_duration_minutes,
        actual_distance_km=actual_distance_km,
    )

    if is_completed:
        system_prompt = (
            "You are an AI endurance coach providing post-workout analysis. "
            "Analyze execution, compare to plan, and provide insightful feedback. "
            "Use synthesis and judgment language. Do NOT reference algorithms or rules."
        )
    else:
        system_prompt = (
            "You are an AI endurance coach providing daily execution guidance. "
            "Generate actionable instructions, structured steps, and insightful reasoning. "
            "Use synthesis and judgment language. Do NOT reference algorithms or rules."
        )

    agent = Agent(
        model=model,
        system_prompt=system_prompt,
        output_type=TodaySessionContent,
    )

    try:
        logger.info("Generating today session content", session_title=session_title)

        log_llm_request(
            context="Today Session Content Generation",
            system_prompt=system_prompt,
            user_prompt=prompt,
        )

        result = await agent.run(prompt)
        log_llm_raw_response(
            context="Today Session Content Generation",
            result=result,
        )

        content = result.output
        _validate_content_type(content)

        log_llm_extracted_fields(
            context="Today Session Content Generation",
            parsed_output=content,
        )

        logger.info(
            "Today session content generated",
            instructions_count=len(content.instructions),
            steps_count=len(content.steps),
            has_insight=bool(content.coach_insight),
        )
    except Exception as e:
        logger.error(
            "Failed to generate today session content",
            error_type=type(e).__name__,
            error=str(e),
        )
        raise RuntimeError(f"LLM generation failed: {e!s}") from e
    else:
        return content
