from langchain_core.prompts import ChatPromptTemplate
from langchain_openai import ChatOpenAI
from loguru import logger
from pydantic import SecretStr

from app.coach.models import AthleteState
from app.core.settings import settings

COLD_START_INSTRUCTIONS = """
You are AI Coach — an elite endurance training intelligence system.

This is the first time you're speaking with this athlete. Talk like a human coach having a casual conversation.

Rules:
- Keep it SHORT: 1-2 sentences maximum, not paragraphs
- Be conversational and natural, like a real person
- If data is missing or limited, ASK QUESTIONS to understand their goals
- Don't list all your capabilities — just be friendly and helpful
- No formal introductions — just start chatting naturally

If athlete state is provided:
- Give ONE brief observation about their training state
- Keep it casual and human-sounding
- No metrics or technical terms — just natural language

If no athlete state is provided:
- Ask them what they're training for or what they need help with
- Don't explain what you can do — just be ready to help

Examples:
BAD: "Hello and welcome! I'm your Coach, your dedicated AI training coach
here to support you on your endurance journey. My role is to help you..."

GOOD: "Hey! I'm your Coach. I see your training looks solid — how can I help you today?"

GOOD (no data): "Hi! What are you training for? I'd love to help you reach your goals."

Return ONLY the message text. No metadata or structure. Keep it under 50 words.
"""

if not settings.openai_api_key:
    _cold_start_llm = None
    logger.warning("OPENAI_API_KEY is not set. Cold start LLM features will not work.")
else:
    _cold_start_llm = ChatOpenAI(
        model="gpt-4o-mini",
        temperature=0.3,
        api_key=SecretStr(settings.openai_api_key),
    )

_cold_start_prompt = ChatPromptTemplate.from_messages([
    ("system", COLD_START_INSTRUCTIONS),
    ("human", "{context}"),
])

if _cold_start_llm is not None:
    _cold_start_chain = _cold_start_prompt | _cold_start_llm
else:
    _cold_start_chain = None


def welcome_new_user(state: AthleteState | None = None) -> str:
    """Generate a welcome message using the LLM agent for new users.

    Args:
        state: Optional athlete state. If provided, includes personalized information.

    Returns:
        A welcoming message generated by the LLM introducing the coach and its capabilities.
    """
    if _cold_start_chain is None or not settings.openai_api_key:
        logger.warning("LLM not available for cold start, using fallback message")
        if state is not None:
            fallback = "Hey! I see your training looks good. What can I help you with today?"
        else:
            fallback = "Hi! What are you training for? I'd love to help you reach your goals."
        return fallback

    # Build context for the LLM
    if state is not None:
        context = f"""Generate a short, casual welcome message (1-2 sentences max).

Athlete's training state:
- Fitness level: {state.ctl:.1f}
- Fatigue: {state.atl:.1f}
- Form: {state.tsb:.1f}
- Trend: {state.load_trend}
- Flags: {", ".join(state.flags) if state.flags else "none"}

Give ONE brief, natural observation about their training. Then ask how you can help.
Keep it conversational, like a human coach would talk."""
    else:
        context = (
            "Generate a short, casual welcome message (1-2 sentences max). "
            "No training data available yet. Ask them what they're training for or what they need help with. "
            "Be conversational and natural — like a real person, not a formal introduction."
        )

    try:
        logger.info("Generating cold start welcome message with LLM")
        response = _cold_start_chain.invoke({"context": context})
        # Chain returns AIMessage with .content attribute
        # Extract string content, handling potential list/str types
        content = response.content
        if isinstance(content, str):
            message = content
        elif isinstance(content, list):
            # If content is a list, join all string elements
            message = " ".join(str(item) for item in content if isinstance(item, str))
        else:
            message = str(content)
        logger.info("Cold start message generated successfully")
    except Exception as e:
        logger.error(f"Error generating cold start message: {e}", exc_info=True)
        # Fallback to a simple message if LLM fails
        if state is not None:
            fallback = "Hey! I see your training looks good. What can I help you with today?"
        else:
            fallback = "Hi! What are you training for? I'd love to help you reach your goals."
        return fallback
    else:
        return message
