"""Structural schemas for LLM-generated training intents.

These schemas define the structure of training decisions generated by the LLM.
They contain NO logic, NO computed fields, and NO formulas.
They are pure data containers for LLM outputs.
"""

from datetime import date
from typing import Literal

from pydantic import BaseModel, Field


class Confidence(BaseModel):
    """Confidence score with explanation for a training decision."""

    score: float = Field(
        ...,
        description="Confidence score (0.0 to 1.0)",
        ge=0.0,
        le=1.0,
    )
    explanation: str = Field(
        ...,
        description="Human-readable explanation of the confidence level. Must be calm and coach-like.",
        min_length=20,
        max_length=200,
    )


class SeasonPlan(BaseModel):
    """LLM-generated season-level training plan.

    This represents the high-level training strategy for a season,
    typically 12-24 weeks. Generated by the LLM based on athlete goals,
    current fitness, and race calendar.
    """

    # Core plan attributes
    focus: str = Field(
        ...,
        description="Primary training focus for the season (e.g., 'Base building', 'Race preparation', 'Recovery')",
        min_length=10,
        max_length=200,
    )
    volume_range: str = Field(
        ...,
        description="Target weekly volume range in hours (e.g., '8-12 hours/week')",
        min_length=5,
        max_length=50,
    )
    intensity_density: str = Field(
        ...,
        description="Intensity distribution strategy (e.g., '80/20 polarized', 'Pyramidal', 'Threshold-focused')",
        min_length=5,
        max_length=100,
    )
    adaptation_goal: str = Field(
        ...,
        description="Primary physiological adaptation goal (e.g., 'Aerobic capacity', 'Lactate threshold', 'VO2 max')",
        min_length=10,
        max_length=150,
    )

    # Risk and confidence
    risk_notes: str = Field(
        ...,
        description="Identified risks and mitigation strategies for the season",
        min_length=20,
        max_length=500,
    )
    confidence: float = Field(
        ...,
        description="Confidence in this plan (0.0 to 1.0)",
        ge=0.0,
        le=1.0,
    )

    # Explanation (first-class field)
    explanation: str = Field(
        ...,
        description="Human-readable explanation of the season plan. Must be calm, conservative, and coach-like.",
        min_length=100,
        max_length=1000,
    )

    # Metadata
    season_start: date = Field(..., description="Start date of the season plan")
    season_end: date = Field(..., description="End date of the season plan")
    target_races: list[str] = Field(
        default_factory=list,
        description="List of target races or events during this season",
    )


class WeeklyIntent(BaseModel):
    """LLM-generated weekly training intent.

    This represents the training intent for a specific week,
    conditioned on the current SeasonPlan and recent training data.
    Generated by the LLM to guide daily decisions.
    """

    # Core intent attributes
    focus: str = Field(
        ...,
        description="Primary focus for this week (e.g., 'Volume accumulation', 'Recovery', 'Intensity block')",
        min_length=10,
        max_length=200,
    )
    volume_target_hours: float = Field(
        ...,
        description="Target weekly volume in hours",
        ge=0.0,
        le=30.0,
    )
    intensity_distribution: str = Field(
        ...,
        description="Intensity distribution for the week (e.g., '2 hard sessions, 4 easy sessions, 1 rest day')",
        min_length=10,
        max_length=300,
    )
    adaptation_goal: str = Field(
        ...,
        description="Primary adaptation goal for this week",
        min_length=10,
        max_length=150,
    )

    # Risk and confidence
    risk_notes: str = Field(
        ...,
        description="Risks specific to this week and how to mitigate them",
        min_length=20,
        max_length=500,
    )
    confidence: float = Field(
        ...,
        description="Confidence in this weekly intent (0.0 to 1.0)",
        ge=0.0,
        le=1.0,
    )

    # Explanation (first-class field)
    explanation: str = Field(
        ...,
        description="Human-readable explanation of the weekly intent. Must be calm, conservative, and coach-like.",
        min_length=100,
        max_length=1000,
    )

    # Context
    week_start: date = Field(..., description="Start date of the week (Monday)")
    week_number: int = Field(..., description="Week number within the season plan", ge=1)
    season_plan_id: str | None = Field(
        default=None,
        description="Reference to the season plan this week belongs to",
    )


class WeeklyReport(BaseModel):
    """LLM-generated weekly coach report.

    This represents a weekly summary explaining progress, changes, and next focus.
    Generated automatically at the end of each week.
    """

    # Core report attributes
    week_summary: str = Field(
        ...,
        description="High-level summary of the week's training and outcomes",
        min_length=100,
        max_length=500,
    )
    progress_highlights: list[str] = Field(
        ...,
        description="Key progress points from the week (2-4 items)",
        min_length=2,
        max_length=4,
    )
    changes_explained: str = Field(
        ...,
        description="Explanation of any changes made during the week and why",
        min_length=50,
        max_length=400,
    )
    next_focus: str = Field(
        ...,
        description="Primary focus for the upcoming week",
        min_length=50,
        max_length=300,
    )
    risk_observations: str | None = Field(
        default=None,
        description="Observations about risk or fatigue (if any)",
        min_length=20,
        max_length=300,
    )

    # Context
    week_start: date = Field(..., description="Start date of the week (Monday)")
    week_end: date = Field(..., description="End date of the week (Sunday)")


class DailyDecision(BaseModel):
    """LLM-generated daily training decision.

    This represents the training decision for a specific day,
    conditioned on the current WeeklyIntent and recent training data.
    Generated by the LLM to provide actionable guidance.
    """

    # Core decision attributes
    recommendation: Literal["rest", "easy", "moderate", "hard", "race"] = Field(
        ...,
        description="Training recommendation for the day",
    )
    volume_hours: float | None = Field(
        default=None,
        description="Recommended training volume in hours (null for rest days)",
        ge=0.0,
        le=6.0,
    )
    intensity_focus: str | None = Field(
        default=None,
        description="Intensity focus for the day (e.g., 'Zone 2 aerobic', 'Threshold intervals', 'VO2 max')",
        min_length=5,
        max_length=100,
    )
    session_type: str | None = Field(
        default=None,
        description="Type of session (e.g., 'Long run', 'Tempo run', 'Recovery jog', 'Rest day')",
        min_length=5,
        max_length=100,
    )

    # Risk and confidence
    risk_level: Literal["none", "low", "medium", "high"] = Field(
        ...,
        description="Risk level for this day's training",
    )
    risk_notes: str | None = Field(
        default=None,
        description="Specific risk considerations for this day",
        min_length=10,
        max_length=300,
    )
    confidence: Confidence = Field(
        ...,
        description="Confidence in this daily decision with explanation",
    )

    # Explanation (first-class field)
    explanation: str = Field(
        ...,
        description="Human-readable explanation of the daily decision. Must be calm, conservative, and coach-like.",
        min_length=50,
        max_length=500,
    )

    # Context
    decision_date: date = Field(..., description="Date for which this decision applies")
    weekly_intent_id: str | None = Field(
        default=None,
        description="Reference to the weekly intent this day belongs to",
    )
