"""Structural schemas for LLM-generated training intents.

These schemas define the structure of training decisions generated by the LLM.
They contain NO logic, NO computed fields, and NO formulas.
They are pure data containers for LLM outputs.
"""

from datetime import date
from typing import Literal

from pydantic import BaseModel, Field


class Confidence(BaseModel):
    """Confidence score with explanation for a training decision."""

    score: float = Field(
        ...,
        description="Confidence score (0.0 to 1.0). Must be between 0.0 and 1.0.",
    )
    explanation: str = Field(
        ...,
        description="Human-readable explanation of the confidence level (20-200 chars). Must be calm and coach-like.",
    )


class SeasonPlan(BaseModel):
    """LLM-generated season-level training plan.

    This represents the high-level training strategy for a season,
    typically 12-24 weeks. Generated by the LLM based on athlete goals,
    current fitness, and race calendar.
    """

    # Core plan attributes
    focus: str = Field(
        ...,
        description="Primary training focus for the season (e.g., 'Base building', 'Race preparation', 'Recovery'). 10-200 chars.",
    )
    volume_range: str = Field(
        ...,
        description="Target weekly volume range in hours (e.g., '8-12 hours/week'). 5-50 chars.",
    )
    intensity_density: str = Field(
        ...,
        description="Intensity distribution strategy (e.g., '80/20 polarized', 'Pyramidal', 'Threshold-focused'). 5-100 chars.",
    )
    adaptation_goal: str = Field(
        ...,
        description="Primary physiological adaptation goal (e.g., 'Aerobic capacity', 'Lactate threshold', 'VO2 max'). 10-150 chars.",
    )

    # Risk and confidence
    risk_notes: str = Field(
        ...,
        description="Identified risks and mitigation strategies for the season. 20-500 chars.",
    )
    confidence: float = Field(
        ...,
        description="Confidence in this plan (0.0 to 1.0). Must be between 0.0 and 1.0.",
    )

    # Explanation (first-class field)
    explanation: str = Field(
        ...,
        description="Human-readable explanation of the season plan. Must be calm, conservative, and coach-like. 100-1000 chars.",
    )

    # Metadata
    season_start: date = Field(..., description="Start date of the season plan")
    season_end: date = Field(..., description="End date of the season plan")
    target_races: list[str] = Field(
        default_factory=list,
        description="List of target races or events during this season",
    )


class WeeklyIntent(BaseModel):
    """LLM-generated weekly training intent.

    This represents the training intent for a specific week,
    conditioned on the current SeasonPlan and recent training data.
    Generated by the LLM to guide daily decisions.
    """

    # Core intent attributes
    focus: str = Field(
        ...,
        description="Primary focus for this week (e.g., 'Volume accumulation', 'Recovery', 'Intensity block'). 10-200 chars.",
    )
    volume_target_hours: float = Field(
        ...,
        description="Target weekly volume in hours. Must be between 0.0 and 30.0.",
    )
    intensity_distribution: str = Field(
        ...,
        description="Intensity distribution for the week (e.g., '2 hard sessions, 4 easy sessions, 1 rest day'). 10-300 chars.",
    )
    adaptation_goal: str = Field(
        ...,
        description="Primary adaptation goal for this week. 10-150 chars.",
    )

    # Risk and confidence
    risk_notes: str = Field(
        ...,
        description="Risks specific to this week and how to mitigate them. 20-500 chars.",
    )
    confidence: float = Field(
        ...,
        description="Confidence in this weekly intent (0.0 to 1.0). Must be between 0.0 and 1.0.",
    )

    # Explanation (first-class field)
    explanation: str = Field(
        ...,
        description="Human-readable explanation of the weekly intent. Must be calm, conservative, and coach-like. 100-1000 chars.",
    )

    # Context
    week_start: date = Field(..., description="Start date of the week (Monday)")
    week_number: int = Field(..., description="Week number within the season plan. Must be at least 1.")
    season_plan_id: str | None = Field(
        default=None,
        description="Reference to the season plan this week belongs to",
    )


class WeeklyReport(BaseModel):
    """LLM-generated weekly coach report.

    This represents a weekly summary explaining progress, changes, and next focus.
    Generated automatically at the end of each week.
    """

    # Core report attributes
    week_summary: str = Field(
        ...,
        description="High-level summary of the week's training and outcomes. 100-500 chars.",
    )
    progress_highlights: list[str] = Field(
        ...,
        description="Key progress points from the week. Must have 2-4 items.",
    )
    changes_explained: str = Field(
        ...,
        description="Explanation of any changes made during the week and why. 50-400 chars.",
    )
    next_focus: str = Field(
        ...,
        description="Primary focus for the upcoming week. 50-300 chars.",
    )
    risk_observations: str | None = Field(
        default=None,
        description="Observations about risk or fatigue (if any). 20-300 chars when provided.",
    )

    # Context
    week_start: date = Field(..., description="Start date of the week (Monday)")
    week_end: date = Field(..., description="End date of the week (Sunday)")


class DailyDecision(BaseModel):
    """LLM-generated daily training decision.

    This represents the training decision for a specific day,
    conditioned on the current WeeklyIntent and recent training data.
    Generated by the LLM to provide actionable guidance.
    """

    # Core decision attributes
    recommendation: Literal["rest", "easy", "easy_with_caution", "moderate", "moderate_with_caution", "hard", "race"] = Field(
        ...,
        description="Training recommendation for the day",
    )
    volume_hours: float | None = Field(
        default=None,
        description="Recommended training volume in hours (null for rest days). Must be between 0.0 and 6.0 when provided.",
    )
    intensity_focus: str | None = Field(
        default=None,
        description="Intensity focus for the day (e.g., 'Zone 2 aerobic', 'Threshold intervals', 'VO2 max'). 5-100 chars when provided.",
    )
    session_type: str | None = Field(
        default=None,
        description="Type of session (e.g., 'Long run', 'Tempo run', 'Recovery jog', 'Rest day'). 5-100 chars when provided.",
    )

    # Risk and confidence
    risk_level: Literal["none", "low", "medium", "high"] = Field(
        ...,
        description="Risk level for this day's training",
    )
    risk_notes: str | None = Field(
        default=None,
        description="Specific risk considerations for this day. 10-300 chars when provided.",
    )
    confidence: Confidence = Field(
        ...,
        description="Confidence in this daily decision with explanation",
    )

    # Explanation (first-class field)
    explanation: str = Field(
        ...,
        description="Human-readable explanation of the daily decision. Must be calm, conservative, and coach-like. 50-500 chars.",
    )

    # Context
    decision_date: date = Field(..., description="Date for which this decision applies")
    weekly_intent_id: str | None = Field(
        default=None,
        description="Reference to the weekly intent this day belongs to",
    )


class WeeklyCoachSummary(BaseModel):
    """LLM-generated weekly coach summary for season narrative.

    This is a brief 1-2 sentence summary explaining how a week
    unfolded relative to the plan intent, used in the season narrative view.
    """

    summary: str = Field(
        ...,
        description="Brief coach summary (1-2 sentences, 50-300 chars) explaining how the week unfolded relative to plan intent",
    )
