"""Canonical training plan schemas for LLM-generated plans.

These schemas define the exact structure that LLM must return for training plans.
NO rule-based generation should produce these - ONLY LLM.
"""

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field


class TrainingSession(BaseModel):
    """Single training session in a plan. Generated by LLM only."""

    date: datetime = Field(..., description="Session date and time")
    sport: Literal["run", "bike", "swim", "strength", "rest"] = Field(
        ...,
        description="Sport type (lowercase for LLM output, will be mapped to capitalized 'type' field for database)",
    )
    title: str = Field(..., description="Session title (e.g., 'Long Run', 'Tempo Intervals')")
    description: str = Field(..., description="Detailed session description")
    duration_minutes: int | None = Field(default=None, description="Duration in minutes")
    distance_km: float | None = Field(default=None, description="Distance in kilometers")
    intensity: Literal["easy", "moderate", "hard", "race"] = Field(..., description="Session intensity")
    purpose: str = Field(..., description="Purpose of this session")
    week_number: int = Field(..., description="Week number in the plan", ge=1)


class TrainingPlan(BaseModel):
    """Complete training plan. Generated by LLM only.

    This is the ONLY format for training plans.
    All rule-based generation paths are removed.
    """

    plan_type: Literal["race", "season", "weekly"] = Field(..., description="Type of training plan")
    rationale: str = Field(..., description="Explanation of the plan's rationale and approach")
    assumptions: list[str] = Field(default_factory=list, description="Assumptions made in planning")
    sessions: list[TrainingSession] = Field(default_factory=list, description="List of training sessions")
