"""Migration script to create conversation_summaries table (B35).

This migration creates:
- conversation_summaries: Append-only, versioned storage for conversation summaries
  - id: UUID primary key
  - conversation_id: Conversation ID (indexed)
  - version: Monotonically increasing version number (starts at 1)
  - summary: JSONB structured summary (facts, preferences, goals, open_threads)
  - created_at: Timestamp when summary was created (server-generated, UTC)

Constraints:
- Unique constraint: (conversation_id, version) prevents duplicates
- Index on (conversation_id, version DESC) for O(1) latest retrieval
- Append-only (no updates or deletes)

This table is the source of truth for conversation summaries. Redis is cache-only.
"""

import sys
from pathlib import Path

# Add project root to Python path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

from loguru import logger
from sqlalchemy import text

from app.config.settings import settings
from app.db.session import engine


def _is_postgresql() -> bool:
    """Check if database is PostgreSQL."""
    return "postgresql" in settings.database_url.lower() or "postgres" in settings.database_url.lower()


def _table_exists(conn, table_name: str) -> bool:
    """Check if table exists."""
    if _is_postgresql():
        result = conn.execute(
            text("SELECT tablename FROM pg_tables WHERE schemaname = 'public' AND tablename = :table_name"),
            {"table_name": table_name},
        )
        return result.fetchone() is not None
    # SQLite
    result = conn.execute(
        text("SELECT name FROM sqlite_master WHERE type='table' AND name=:table_name"),
        {"table_name": table_name},
    )
    return result.fetchone() is not None


def migrate_add_conversation_summaries_table() -> None:
    """Create conversation_summaries table if it doesn't exist."""
    logger.info("Starting conversation_summaries table migration (B35)")
    db_type = "PostgreSQL" if _is_postgresql() else "SQLite"
    logger.info(f"Database type: {db_type}")

    with engine.begin() as conn:
        try:
            # Check if table already exists
            if _table_exists(conn, "conversation_summaries"):
                logger.info("conversation_summaries table already exists, skipping migration")
                return

            logger.info("Creating conversation_summaries table...")

            if _is_postgresql():
                # PostgreSQL: Use VARCHAR for id (generated by SQLAlchemy), JSONB, TIMESTAMP WITH TIME ZONE
                # Note: id is generated by SQLAlchemy using Python uuid.uuid4(), not database default
                conn.execute(
                    text(
                        """
                        CREATE TABLE conversation_summaries (
                            id VARCHAR PRIMARY KEY,
                            conversation_id VARCHAR NOT NULL,
                            version INTEGER NOT NULL,
                            summary JSONB NOT NULL,
                            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                            CONSTRAINT uq_conversation_summary_version UNIQUE (conversation_id, version)
                        )
                        """
                    )
                )

                # Create indexes
                conn.execute(
                    text(
                        """
                        CREATE INDEX idx_conversation_summary_latest
                        ON conversation_summaries (conversation_id, version DESC)
                        """
                    )
                )

                conn.execute(
                    text(
                        """
                        CREATE INDEX idx_conversation_summaries_conversation_id
                        ON conversation_summaries (conversation_id)
                        """
                    )
                )
            else:
                # SQLite: Use TEXT, TEXT (for JSON), DATETIME
                conn.execute(
                    text(
                        """
                        CREATE TABLE conversation_summaries (
                            id TEXT PRIMARY KEY,
                            conversation_id TEXT NOT NULL,
                            version INTEGER NOT NULL,
                            summary TEXT NOT NULL,
                            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            UNIQUE(conversation_id, version)
                        )
                        """
                    )
                )

                # Create indexes
                conn.execute(
                    text(
                        """
                        CREATE INDEX idx_conversation_summary_latest
                        ON conversation_summaries (conversation_id, version DESC)
                        """
                    )
                )

                conn.execute(
                    text(
                        """
                        CREATE INDEX idx_conversation_summaries_conversation_id
                        ON conversation_summaries (conversation_id)
                        """
                    )
                )

            logger.info("Conversation_summaries table created successfully")

        except Exception as e:
            logger.error(f"Error during conversation_summaries table migration: {e}", exc_info=True)
            raise


if __name__ == "__main__":
    migrate_add_conversation_summaries_table()
